services:
  redis:
    image: redislabs/rejson
    restart: always

  worker:
    build: .
    restart: always
    environment:
      - MONGO_URI
      - IDENT
    depends_on:
      - redis
    command: dramatiq dramatiq_actors:redis_broker

  scanner:
    build: .
    restart: always
    environment:
      - RATE
      - MONGO_URI
    depends_on:
      - worker
    command: python3 -m scanner
